name: fragrantica_wrapper
description: "A package which acts as a wrapper for the Fragrantica website. Educational purposes only."
version: 0.0.2
repository: https://github.com/oscarspalk/fragrantica_wrapper
environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  beautiful_soup_dart: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
